### ISSUE TITLE
Clarification on RageDB

### ISSUE THREAD

**Issue by lonnietc** [ragedb/ragedb#33]
Hello,

I have been reading about your RageDB project since I am searching for a core system that I can build on for a project that will be using MSYS2/MinGW64 but am a bit confused.

Is RageDB an independent property graph database or is it a layer on this other project that was referred here called Seastar?

I am not sure what Seastar is.

I need to locate a simple in-memory property graph library and am wondering if RageDB could be converted for that purpose as it would be integrated with some other libraries for a particular graph database project.

Also, can RageDB be ported to MinGW?

**Comment by maxdemarzi** [comment]
https://seastar.io/ is a dependency of RageDB, and it can run only on [Linux](http://kernel.org/) or [OSv](http://osv.io/).

**Comment by lonnietc** [comment]
Thanks for getting back to me on this and I understand.

If you happen to make things to be able to compile and run under Mingw then I will look back again in the future since I think that RageDB has nice potential but will not work for my project in its current state.

Cheers
