### ISSUE TITLE
Running Docker image on Mac M1

### ISSUE THREAD

**Issue by danve** [ragedb/ragedb#34]
I do try to run the docker on MacBook with Apple M1 Max chip

The result is bellow. How to approach it? 

Mention: I intend only use the DB, not develop, so may be there a simplier (or already compiled) DB engine

```
docker run -u 0 -p 127.0.0.1:7243:7243 --name ragedb -t dockerhub.ragedb.com/ragedb/ragedb:latest --cap-add=sys_nice
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Killed
```

Thanks

**Comment by maxdemarzi** [comment]
Hello! Thank you for bringing this up. I tried building a multi architecture docker image and pushing it but it errored out. Just realized I had not pushed to Docker Hub in months! I'll get on it and fix this tomorrow hopefully.

**Comment by maxdemarzi** [comment]
Having a problem building the docker image for the arm64 architecture.

Trying to run this command:

     docker buildx build --platform linux/arm64  -t ragedb/ragedb:latest --push .

But I get this error:

    #0 22.76 /usr/bin/ld: /root/.conan/data/luajit/2.1.0-beta3-2022-7-22/_/_/package/115c8fa606e08a868a5ec8073c26c1a096c7263b/lib/libluajit-5.1.so: error adding symbols: file in wrong format
    #0 22.77 collect2: error: ld returned 1 exit status
    #0 22.80 gmake[2]: *** [CMakeFiles/test_package.dir/build.make:98: bin/test_package] Error 1
    #0 22.80 gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/test_package.dir/all] Error 2
    #0 22.81 gmake: *** [Makefile:91: all] Error 2
    #0 22.85 ERROR: luajit/2.1.0-beta3-2022-7-22 (test package): Error in build() method, line 12
    #0 22.85 	cmake.build()
    #0 22.85 	ConanException: Error 2 while executing cmake --build '/data/luajit/test_package/build/b4fc232286346fa3046bf24c2af61902d21a6bce' '--' '-j8'
    ------
    Dockerfile:21
    --------------------
      19 |     RUN conan profile update settings.compiler.libcxx=libstdc++11 default
      20 |     RUN conan profile update settings.arch=armv8 default
      21 | >>> RUN conan create . 2.1.0-beta3-2022-7-22@
      22 |     RUN git clone https://github.com/ragedb/sol2-recipe.git /data/sol2
      23 |     WORKDIR /data/sol2
    --------------------
    ERROR: failed to solve: process "/bin/sh -c conan create . 2.1.0-beta3-2022-7-22@" did not complete successfully: exit code: 1

I tried adding this to the dockerfile before any conan builts, but no luck.

    RUN conan profile new default --detect
    RUN conan profile update settings.compiler.libcxx=libstdc++11 default
    RUN conan profile update settings.arch=armv8 default

**Comment by danve** [comment]
thanks for trying out,

**Comment by PatLechevallier** [comment]
Re, I saw your last commits. There probably related to this ticket.
Can we have a new docker image ? Like M1 compatible for now

**Comment by maxdemarzi** [comment]
Trying... and failing so far... it shouldn't be this hard, but c'est la vie

**Comment by maxdemarzi** [comment]
After DAYS spent on this: https://hub.docker.com/r/ragedb/ragedb/tags 
Try it and let me know if it worked correctly

**Comment by maxdemarzi** [comment]
Do this:

docker pull dockerhub.ragedb.com/ragedb/ragedb:arm64-latest
docker run -u 0 -p 127.0.0.1:7243:7243 --name ragedb -t dockerhub.ragedb.com/ragedb/ragedb:arm64-latest --cap-add=sys_nice

Then open a browser to http://0.0.0.0:7243

**Comment by PatLechevallier** [comment]
Seems to work!

`WARNING: unable to mbind shard memory; performance may suffer: 
WARN  2022-10-23 13:03:24,639 [shard 0] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
INFO  2022-10-23 13:03:24,640 [shard 0] seastar - Created fair group io-queue-0, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000
INFO  2022-10-23 13:03:24,640 [shard 0] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
INFO  2022-10-23 13:03:24,640 [shard 0] seastar - Created io queue dev(0) capacities: 512:2000/2000 1024:3000/3000 2048:5000/5000 4096:9000/9000 8192:17000/17000 16384:33000/33000 32768:65000/65000 65536:129000/129000 131072:257000/257000
WARNING: unable to mbind shard memory; performance may suffer: 
WARN  2022-10-23 13:03:24,649 [shard 2] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARN  2022-10-23 13:03:24,651 [shard 3] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2022-10-23 13:03:24,651 [shard 1] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
RageDB running on 4 cores.
Logging disabled 
RageDB HTTP server listening on 0.0.0.0:7243 ...`


Thank you very Much! I am gonna try this further. Sorry I cannot help as I have no experience with c++. I am going to try to implement Lua into Java code with the help of https://sourceforge.net/projects/luaj/
